### ISSUE TITLE
Pass parent RPC to the verify-token-bridge script

### ISSUE THREAD

**Issue by alxdca** [OffchainLabs/arbitrum-orbit-sdk#69]
The instantiation of the OrbitHandler in the verify-token-bridge script is likely missing the parent RPC, here: https://github.com/OffchainLabs/arbitrum-orbit-sdk/blob/ddc53b6496ee3e228ca9a39a310e2c76ce488b98/examples/verify-rollup/src/verify-token-bridge.ts#L44

**Comment by TucksonDev** [comment]
Hey @alxdca , let me answer you here, even though this is an old issue. We take the default RPC offered by viem for all chains, although the script can be adjusted to also send a [parent chain's RPC](https://github.com/OffchainLabs/arbitrum-orbit-sdk/blob/ddc53b6496ee3e228ca9a39a310e2c76ce488b98/examples/verify-rollup/src/lib/client.ts#L13).

However, the verification script hasn't been updated for a while and it might not work with the latest additions to Orbit. Because of that, I'll close this issue now. If the verification script is updated and you bump into another issue, feel free to open a new one.

Thanks!
